### PR TITLE
ProjectsPage

### PR DESCRIPTION
**Pull request by adityamishra9**
to do : add all projects and relevant description and name as mentioned in [main site](https://yashpede.in)

### CODE REVIEW

**Comment by Yash-pede** [comment]
Attach final screenshot and I'll merge after reviewing

**Comment by adityamishra9** [comment]
> Attach final screenshot and I'll merge after reviewing

yes I'll get it done

**Comment by Yash-pede** [comment]
Why is the hero section not visible ??
ss

**Comment by adityamishra9** [comment]
> Why is the hero section not visible ?? ss

Haa been commented for easy and faster development

**Comment by Yash-pede** [comment]
> > Why is the hero section not visible ?? ss
> 
> Haa been commented for easy and faster development

Great 👍 remember to uncomment it later

**Comment by Yash-pede** [comment]
The skills tags are not working properly
It only shows first row

**Review by Yash-pede — APPROVED** [review]
LGMT

**Pull request merged**
